<template>
    <div>

        <button @click="call_api">Roll</button>


        <button @click="logout_button">logout</button>

    </div>
</template>

<script>
import axios from 'axios';
import Cookies from 'vue-cookies';
    export default {
        
        data() {
            return {

                //variables for win an loss counts//

                win_count_obj: 0,

                lose_count_obj: 0,

            }
        },
   
        methods:{


            logout_button(){

                //logs user out, removes login cookie.//

                Cookies.remove(`login_token`);

                this.$router.push(`/`);

            },


            roll(){

                //called by a successful api call//

                //makes roll amount = the amount stored in the roll cookie//

               let roll_amount = Cookies.get(`roll`);

               //globally emits the roll amount as roll_display//

               this.$root.$emit(`roll_display`, roll_amount);


               if(roll_amount >= 50){

                //if the roll amount is greater than 50, increases the win_count_obj by 1//

                this.win_count_obj +=1

                //emits the win_count_obj as win_display//

                this.$root.$emit(`win_display`, this.win_count_obj);

                //if roll amount is less than 50 it will execute these lines instead//

               }else if(roll_amount <50){

                //same process, but with loss amounts//

           

                this.lose_count_obj +=1;

                this.$root.$emit(`loss_display`, this.lose_count_obj);


               }

               

            },


            call_api(){


                //api called by button click//

                axios({


                    method: `GET`,

                    url: `http://www.randomnumberapi.com/api/v1.0/randomnumber`,



                }).then((response) =>{


                    response;

                    //stores the number generated by the api in a cookie//

                    Cookies.set(`roll`, `${response[`data`][0]}`);


                    //calls the roll function//

                    this.roll();
                    

      


                }).catch((error) =>{


                    error;

                    //console logs an error message if API fails.//

                    console.log(`api failure`);

                });

            },
   

            
        }
   

   }
</script>

<style scoped>

</style>